### ISSUE TITLE
Multiple .csproj files missing

### ISSUE THREAD

**Issue by JohnSmith2007** [maxton/rb-bot#1]
C:\Users\smcco\Downloads\rb-bot-master\rb-bot-master\Dependencies\LibForge\LibForge\LibForge\LibForge.csproj : error  : The project file 'C:\Users\smcco\Downloads\rb-bot-master\rb-bot-master\Dependencies\LibForge\LibForge\LibForge\LibForge.csproj' has been moved, renamed or is not on your computer.

C:\Users\smcco\Downloads\rb-bot-master\rb-bot-master\Dependencies\LibForge\Dependencies\GameArchives\Library\GameArchives.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\Users\smcco\Downloads\rb-bot-master\rb-bot-master\Dependencies\LibForge\Dependencies\GameArchives\Library\GameArchives.csproj'.  C:\Users\smcco\Downloads\rb-bot-master\rb-bot-master\Dependencies\LibForge\Dependencies\GameArchives\Library\GameArchives.csproj

Why are neither of these files included in their reposotories? WTF?

**Comment by maxton** [comment]
First time using git? You need to clone the submodules
https://git-scm.com/book/en/v2/Git-Tools-Submodules
